"use client";

import { useState, useEffect, useCallback } from "react";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, Area, AreaChart } from "recharts";

/* ── Safe storage ── */
const safeGet=k=>{try{if(typeof window!=="undefined")return localStorage.getItem(k);}catch(e){}return null;};
const safeSet=(k,v)=>{try{if(typeof window!=="undefined")localStorage.setItem(k,v);}catch(e){}};
const safeSGet=k=>{try{if(typeof window!=="undefined")return sessionStorage.getItem(k);}catch(e){}return null;};
const safeSSet=(k,v)=>{try{if(typeof window!=="undefined")sessionStorage.setItem(k,v);}catch(e){}};
const safeSRem=k=>{try{if(typeof window!=="undefined")sessionStorage.removeItem(k);}catch(e){}};

const C={bg:"#f2f2f7",card:"#ffffff",border:"rgba(0,0,0,0.06)",text:"#1d1d1f",textSecondary:"#6e6e73",textTertiary:"#aeaeb2",seatRed:"#e3000b",seatBlack:"#1d1d1f",seatDark:"#000000",google:"#4285f4",meta:"#0668E1",positive:"#34c759",positiveBg:"#e5f9ed",negative:"#ff3b30",negativeBg:"#ffe5e7",warning:"#ff9500",shadow:"0 1px 3px rgba(0,0,0,0.04),0 1px 2px rgba(0,0,0,0.06)",shadowMd:"0 4px 12px rgba(0,0,0,0.05),0 1px 3px rgba(0,0,0,0.06)"};
const F="-apple-system,BlinkMacSystemFont,'SF Pro Display','Helvetica Neue',Arial,sans-serif";
const FM="-apple-system,BlinkMacSystemFont,'SF Mono',Menlo,monospace";
const SID="1HEykheeAndB-RXqKy4wehTzrZNZvuQxpv3WuUwSsUuM";
const MONTHS=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];
const QL=["Trimestre 1","Trimestre 2","Trimestre 3","Trimestre 4"];

const fmt=v=>{v=parseFloat(v||0);return v>=1e6?`${(v/1e6).toFixed(1)}M €`:v>=1000?`${(v/1000).toFixed(1)}K €`:`${v.toFixed(2)} €`;};
const fN=v=>{v=parseInt(v||0);return v>=1e6?`${(v/1e6).toFixed(1)}M`:v>=1000?`${(v/1000).toFixed(1)}K`:v.toString();};
const fP=v=>`${parseFloat(v||0).toFixed(2)}%`;
const parseCSV=text=>{const lines=text.trim().split("\n");if(lines.length<2)return[];const hd=lines[0].split(",").map(h=>h.trim().replace(/^"|"$/g,""));return lines.slice(1).map(line=>{const vs=[];let c="",q=false;for(let i=0;i<line.length;i++){if(line[i]==='"')q=!q;else if(line[i]===','&&!q){vs.push(c.trim());c="";}else c+=line[i];}vs.push(c.trim());const o={};hd.forEach((h,i)=>{const v=(vs[i]||"").replace(/^"|"$/g,"");o[h]=isNaN(v)||v===""?v:parseFloat(v);});return o;});};

const SeatLogo=()=>(<svg viewBox="0 0 200 45" style={{height:28}} fill="none"><text x="0" y="33" style={{fontSize:36,fontFamily:F,fontWeight:800,letterSpacing:6,fill:"#fff"}}>SEAT</text><line x1="0" y1="41" x2="165" y2="41" stroke="#e3000b" strokeWidth="2.5"/></svg>);
const Dot=({color,size=8})=>(<span style={{display:"inline-block",width:size,height:size,borderRadius:"50%",background:color,boxShadow:`0 0 4px ${color}44`}}/>);

const LoginScreen=({onLogin})=>{const[e,sE]=useState("");const[p,sP]=useState("");const[err,sErr]=useState("");const[ld,sLd]=useState(false);const go=ev=>{ev.preventDefault();sLd(true);sErr("");setTimeout(()=>{if(e==="marketing@safamotor.com"&&p==="Marketing_26")onLogin(true);else{sErr("Credenciales incorrectas");sLd(false);}},500);};return(<div style={{minHeight:"100vh",background:"linear-gradient(180deg,#000,#1a1a1a)",display:"flex",alignItems:"center",justifyContent:"center",fontFamily:F}}><div style={{width:"100%",maxWidth:380,padding:24}}><div style={{textAlign:"center",marginBottom:48}}><svg viewBox="0 0 200 45" style={{height:44,margin:"0 auto",display:"block"}} fill="none"><text x="22" y="33" style={{fontSize:36,fontFamily:F,fontWeight:800,letterSpacing:6,fill:"#fff"}}>SEAT</text><line x1="22" y1="41" x2="187" y2="41" stroke="#e3000b" strokeWidth="2.5"/></svg><div style={{color:"rgba(255,255,255,0.35)",fontSize:12,marginTop:16,letterSpacing:3,textTransform:"uppercase",fontWeight:500}}>Marketing Dashboard</div></div><div style={{background:"rgba(255,255,255,0.06)",backdropFilter:"blur(40px)",WebkitBackdropFilter:"blur(40px)",borderRadius:16,padding:32,border:"1px solid rgba(255,255,255,0.1)"}}><div style={{fontSize:20,fontWeight:600,color:"#fff",marginBottom:4}}>Iniciar sesión</div><div style={{fontSize:13,color:"rgba(255,255,255,0.4)",marginBottom:28}}>Accede con tus credenciales</div><form onSubmit={go}><div style={{marginBottom:14}}><input type="email" value={e} onChange={ev=>sE(ev.target.value)} placeholder="Email" style={{width:"100%",background:"rgba(255,255,255,0.08)",border:"1px solid rgba(255,255,255,0.12)",borderRadius:10,color:"#fff",fontFamily:F,fontSize:15,padding:"13px 16px",outline:"none",boxSizing:"border-box"}}/></div><div style={{marginBottom:24}}><input type="password" value={p} onChange={ev=>sP(ev.target.value)} placeholder="Contraseña" style={{width:"100%",background:"rgba(255,255,255,0.08)",border:"1px solid rgba(255,255,255,0.12)",borderRadius:10,color:"#fff",fontFamily:F,fontSize:15,padding:"13px 16px",outline:"none",boxSizing:"border-box"}}/></div>{err&&<div style={{background:"rgba(255,59,48,0.15)",borderRadius:10,padding:"10px 14px",marginBottom:16,fontSize:13,color:"#ff6961",fontWeight:500,textAlign:"center"}}>{err}</div>}<button type="submit" disabled={ld} style={{width:"100%",background:"#e3000b",border:"none",borderRadius:10,color:"#fff",fontFamily:F,fontSize:15,fontWeight:600,padding:14,cursor:ld?"wait":"pointer",opacity:ld?0.7:1}}>{ld?"Verificando...":"Acceder"}</button></form></div></div></div>);};

const DatePicker=({sd,ed,onChange})=>{const ps=[{l:"7d",d:7},{l:"15d",d:15},{l:"30d",d:30},{l:"90d",d:90}];const ad=Math.round((new Date(ed)-new Date(sd))/86400000);return(<div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}>{ps.map(p=>(<button key={p.d} onClick={()=>{const e=new Date(),s=new Date(e);s.setDate(s.getDate()-p.d);onChange(s.toISOString().split("T")[0],e.toISOString().split("T")[0]);}} style={{background:ad===p.d?"#1d1d1f":"#fff",color:ad===p.d?"#fff":"#6e6e73",border:`1px solid ${ad===p.d?"#1d1d1f":"#d2d2d7"}`,borderRadius:20,fontFamily:F,fontSize:12,fontWeight:500,padding:"6px 14px",cursor:"pointer"}}>{p.l}</button>))}<div style={{display:"flex",alignItems:"center",gap:4,marginLeft:4}}><input type="date" value={sd} onChange={e=>onChange(e.target.value,ed)} style={{background:"#fff",border:"1px solid #d2d2d7",borderRadius:8,fontFamily:F,fontSize:12,color:C.text,padding:"6px 10px",outline:"none"}}/><span style={{color:"#aeaeb2",fontSize:12}}>→</span><input type="date" value={ed} onChange={e=>onChange(sd,e.target.value)} style={{background:"#fff",border:"1px solid #d2d2d7",borderRadius:8,fontFamily:F,fontSize:12,color:C.text,padding:"6px 10px",outline:"none"}}/></div></div>);};

const MC=({label,total,google,meta})=>(<div style={{background:"#fff",borderRadius:14,padding:"18px 20px",boxShadow:C.shadow,border:`1px solid ${C.border}`}}><div style={{fontSize:11,color:"#aeaeb2",letterSpacing:0.5,textTransform:"uppercase",fontWeight:600,marginBottom:10}}>{label}</div><div style={{fontSize:28,fontWeight:700,color:"#1d1d1f",letterSpacing:-0.5,lineHeight:1}}>{total}</div><div style={{display:"flex",gap:12,marginTop:12,paddingTop:10,borderTop:`1px solid ${C.border}`}}><div style={{display:"flex",alignItems:"center",gap:5,flex:1}}><div style={{width:6,height:6,borderRadius:"50%",background:"#4285f4"}}/><span style={{fontSize:11,color:"#6e6e73"}}>Google</span><span style={{fontSize:12,fontWeight:600,color:"#1d1d1f",marginLeft:"auto",fontFamily:FM}}>{google}</span></div><div style={{width:1,background:C.border}}/><div style={{display:"flex",alignItems:"center",gap:5,flex:1}}><div style={{width:6,height:6,borderRadius:"50%",background:"#0668E1"}}/><span style={{fontSize:11,color:"#6e6e73"}}>Meta</span><span style={{fontSize:12,fontWeight:600,color:"#1d1d1f",marginLeft:"auto",fontFamily:FM}}>{meta}</span></div></div></div>);

const BG=({label,budget,spent,color})=>{const pct=budget>0?(spent/budget)*100:0,rem=budget-spent,gc=pct>90?"#ff3b30":pct>75?"#ff9500":"#34c759";return(<div style={{background:"#fff",borderRadius:14,padding:"18px 20px",boxShadow:C.shadow,border:`1px solid ${C.border}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:8,height:8,borderRadius:"50%",background:color}}/><span style={{fontSize:14,fontWeight:600,color:"#1d1d1f"}}>{label}</span></div><span style={{fontSize:12,fontWeight:600,color:gc,background:gc+"14",padding:"3px 10px",borderRadius:20}}>{pct.toFixed(0)}%</span></div><div style={{background:"#f2f2f7",borderRadius:4,height:5,overflow:"hidden",marginBottom:14}}><div style={{height:"100%",width:`${Math.min(pct,100)}%`,background:gc,borderRadius:4,transition:"width 0.8s"}}/></div><div style={{display:"flex",justifyContent:"space-between"}}><div><div style={{fontSize:10,color:"#aeaeb2",fontWeight:500,marginBottom:2}}>Invertido</div><div style={{fontSize:15,fontWeight:700,color:"#1d1d1f"}}>{fmt(spent)}</div></div><div style={{textAlign:"center"}}><div style={{fontSize:10,color:"#aeaeb2",fontWeight:500,marginBottom:2}}>Presupuesto</div><div style={{fontSize:15,fontWeight:700,color:"#6e6e73"}}>{fmt(budget)}</div></div><div style={{textAlign:"right"}}><div style={{fontSize:10,color:"#aeaeb2",fontWeight:500,marginBottom:2}}>Restante</div><div style={{fontSize:15,fontWeight:700,color:rem<0?"#ff3b30":"#34c759"}}>{fmt(rem)}</div></div></div></div>);};

const BCT=({budgets,ms,cm})=>{const tB=budgets.reduce((s,v)=>s+v,0),tS=Object.values(ms).reduce((s,v)=>s+v,0);const rows=[{l:"Anual",b:tB,s:tS,isH:true}];for(let q=0;q<4;q++){let qB=0,qS=0;for(let m=q*3;m<q*3+3;m++){qB+=budgets[m]||0;qS+=ms[m]||0;}rows.push({l:QL[q],b:qB,s:qS,isQ:true});}MONTHS.forEach((n,i)=>rows.push({l:n,b:budgets[i]||0,s:ms[i]||0,cur:i===cm}));const cs={padding:"10px 14px",fontFamily:F,fontSize:13,borderBottom:`1px solid ${C.border}`};const ns={...cs,textAlign:"right",fontFamily:FM,fontSize:12};return(<div style={{background:"#fff",borderRadius:14,overflow:"hidden",boxShadow:C.shadow,border:`1px solid ${C.border}`}}><div style={{padding:"16px 20px",background:"#1d1d1f",display:"flex",alignItems:"center",gap:8}}><div style={{width:3,height:16,background:"#e3000b",borderRadius:2}}/><span style={{fontSize:13,color:"#fff",fontWeight:600}}>Control de presupuesto</span></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr style={{background:"#fafafa"}}>{["Periodo","Inv. disponible","Inv. consumida","Inv. restante","% disponible"].map(h=><th key={h} style={{...cs,textAlign:h==="Periodo"?"left":"right",fontWeight:600,color:"#aeaeb2",fontSize:10,letterSpacing:0.5,textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=>{const rem=r.b-r.s,pct=r.b>0?((rem/r.b)*100):0;const bg=r.isH?"#e3000b":r.isQ?"#f8f8fa":r.cur?"#fffef0":"#fff";const tc=r.isH?"#fff":"#1d1d1f";const fw=r.isH||r.isQ?700:400;return(<tr key={i} style={{background:bg}}><td style={{...cs,fontWeight:fw,color:tc}}>{r.l}</td><td style={{...ns,fontWeight:fw,color:tc}}>{fmt(r.b)}</td><td style={{...ns,fontWeight:fw,color:tc}}>{fmt(r.s)}</td><td style={{...ns,fontWeight:700,color:rem>=0?(r.isH?"#fff":"#34c759"):"#ff3b30"}}>{fmt(rem)}</td><td style={{...ns}}><span style={{background:pct>=0?(r.isH?"rgba(255,255,255,0.2)":"#e5f9ed"):"#ffe5e7",color:pct>=0?(r.isH?"#fff":"#34c759"):"#ff3b30",padding:"2px 8px",borderRadius:20,fontSize:11,fontWeight:600}}>{r.b>0?`${pct.toFixed(1)}%`:"—"}</span></td></tr>);})}</tbody></table></div></div>);};

const BE=({budgets,onChange})=>{const cs={padding:"10px 14px",fontFamily:F,fontSize:13,borderBottom:`1px solid ${C.border}`};return(<div style={{background:"#fff",borderRadius:14,overflow:"hidden",boxShadow:C.shadow,border:`1px solid ${C.border}`}}><div style={{padding:"16px 20px",background:"#1d1d1f",display:"flex",alignItems:"center",gap:8}}><div style={{width:3,height:16,background:"#e3000b",borderRadius:2}}/><span style={{fontSize:13,color:"#fff",fontWeight:600}}>Presupuesto mensual</span></div><table style={{width:"100%",borderCollapse:"collapse"}}><tbody>{MONTHS.map((n,i)=>(<tr key={i} style={{background:i===new Date().getMonth()?"#fffef0":"#fff"}}><td style={{...cs,fontWeight:500}}>{n}</td><td style={{...cs,textAlign:"right"}}><div style={{display:"flex",alignItems:"center",justifyContent:"flex-end",gap:4}}><input value={budgets[i]} onChange={e=>{const nb=[...budgets];nb[i]=parseFloat(e.target.value)||0;onChange(nb);}} type="number" step="100" style={{background:"#f8f8fa",border:"1px solid #e5e5ea",borderRadius:8,color:"#1d1d1f",fontFamily:FM,fontSize:13,fontWeight:600,padding:"8px 12px",outline:"none",width:120,textAlign:"right",boxSizing:"border-box"}}/><span style={{fontSize:12,color:"#aeaeb2"}}>€</span></div></td></tr>))}{[0,1,2,3].map(q=>{const qt=budgets.slice(q*3,q*3+3).reduce((s,v)=>s+v,0);return(<tr key={`q${q}`} style={{background:"#f8f8fa"}}><td style={{...cs,fontWeight:700}}>{QL[q]}</td><td style={{...cs,textAlign:"right",fontWeight:700,fontFamily:FM}}>{fmt(qt)}</td></tr>);})}<tr style={{background:"#e3000b"}}><td style={{...cs,fontWeight:700,color:"#fff",borderBottom:"none"}}>Total anual</td><td style={{...cs,textAlign:"right",fontWeight:700,color:"#fff",fontSize:16,borderBottom:"none",fontFamily:FM}}>{fmt(budgets.reduce((s,v)=>s+v,0))}</td></tr></tbody></table></div>);};

export default function Dashboard(){
  const[mounted,setMounted]=useState(false);
  const[auth,setAuth]=useState(false);
  const[data,setData]=useState([]);
  const[mb,setMb]=useState([2835,2835,2835,2835,2835,2835,2835,2835,2835,2835,2835,2835]);
  const[view,setView]=useState("overview");
  const[loading,setLoading]=useState(true);
  const[lastUp,setLastUp]=useState(null);
  const[status,setStatus]=useState("loading");
  const td=new Date().toISOString().split("T")[0];
  const d30=new Date(Date.now()-30*86400000).toISOString().split("T")[0];
  const[sd,setSd]=useState(d30);
  const[ed,setEd]=useState(td);

  useEffect(()=>{setMounted(true);if(safeSGet("seat-auth")==="true")setAuth(true);const b=safeGet("seat-budgets-v2");if(b)try{setMb(JSON.parse(b));}catch(e){}},[]);
  const login=ok=>{setAuth(ok);safeSSet("seat-auth","true");};
  const logout=()=>{setAuth(false);safeSRem("seat-auth");};
  const saveMb=nb=>{setMb(nb);safeSet("seat-budgets-v2",JSON.stringify(nb));};

  const fetchData=useCallback(async()=>{setLoading(true);try{const urls=[`https://docs.google.com/spreadsheets/d/${SID}/gviz/tq?tqx=out:csv&sheet=Meta%20Ads`,`https://docs.google.com/spreadsheets/d/${SID}/gviz/tq?tqx=out:csv&sheet=Google%20Ads`];const res=await Promise.allSettled(urls.map(u=>fetch(u).then(r=>r.ok?r.text():"")));let all=[];res.forEach(r=>{if(r.status==="fulfilled"&&r.value)all.push(...parseCSV(r.value));});if(all.length>0){setData(all);setStatus("live");setLastUp(new Date());}else setStatus("empty");}catch(e){setStatus("error");}setLoading(false);},[]);

  useEffect(()=>{if(auth&&mounted)fetchData();},[auth,mounted,fetchData]);
  useEffect(()=>{if(!auth||!mounted)return;const t=setInterval(fetchData,300000);return()=>clearInterval(t);},[auth,mounted,fetchData]);

  if(!mounted)return(<div style={{minHeight:"100vh",background:"#000"}}/>);
  if(!auth)return(<LoginScreen onLogin={login}/>);

  const fd=data.filter(d=>d.fecha&&d.fecha>=sd&&d.fecha<=ed);
  const gD=fd.filter(d=>d.plataforma==="Google Ads"),mD=fd.filter(d=>d.plataforma==="Meta Ads");
  const ag=a=>({sp:a.reduce((s,d)=>s+parseFloat(d.coste||0),0),cl:a.reduce((s,d)=>s+parseInt(d.clics||0),0),im:a.reduce((s,d)=>s+parseInt(d.impresiones||0),0),cv:a.reduce((s,d)=>s+parseFloat(d.conversiones||0),0)});
  const gA=ag(gD),mA=ag(mD),tot={sp:gA.sp+mA.sp,cl:gA.cl+mA.cl,im:gA.im+mA.im,cv:gA.cv+mA.cv};
  const tB=mb.reduce((s,v)=>s+v,0);
  const tCPC=tot.cl>0?tot.sp/tot.cl:0,gCPC=gA.cl>0?gA.sp/gA.cl:0,mCPC=mA.cl>0?mA.sp/mA.cl:0;
  const tCTR=tot.im>0?(tot.cl/tot.im)*100:0,gCTR=gA.im>0?(gA.cl/gA.im)*100:0,mCTR=mA.im>0?(mA.cl/mA.im)*100:0;
  const ms={};data.forEach(d=>{if(!d.fecha)return;const m=parseInt(d.fecha.split("-")[1])-1;ms[m]=(ms[m]||0)+parseFloat(d.coste||0);});
  const dM={};fd.forEach(d=>{const f=d.fecha;if(!f)return;if(!dM[f])dM[f]={fecha:f,google:0,meta:0,clics:0,conv:0};dM[f].clics+=parseInt(d.clics||0);dM[f].conv+=parseFloat(d.conversiones||0);if(d.plataforma==="Google Ads")dM[f].google+=parseFloat(d.coste||0);else dM[f].meta+=parseFloat(d.coste||0);});
  const daily=Object.values(dM).sort((a,b)=>a.fecha.localeCompare(b.fecha));
  const cM={};fd.forEach(d=>{const k=`${d.plataforma}|${d.campaña}`;if(!cM[k])cM[k]={pl:d.plataforma,ca:d.campaña,es:d.estado,co:0,cl:0,im:0,cv:0};cM[k].co+=parseFloat(d.coste||0);cM[k].cl+=parseInt(d.clics||0);cM[k].im+=parseInt(d.impresiones||0);cM[k].cv+=parseFloat(d.conversiones||0);});
  const camps=Object.values(cM).sort((a,b)=>b.co-a.co);
  const piD=[{name:"Google Ads",value:gA.sp,color:"#4285f4"},{name:"Meta Ads",value:mA.sp,color:"#0668E1"}];
  const cm=new Date().getMonth();
  const nb=(v,l)=>(<button key={v} onClick={()=>setView(v)} style={{background:view===v?"#1d1d1f":"transparent",color:view===v?"#fff":"#6e6e73",border:"none",borderRadius:8,fontFamily:F,fontSize:13,fontWeight:500,padding:"7px 16px",cursor:"pointer"}}>{l}</button>);

  return(<div style={{background:"#f2f2f7",minHeight:"100vh",color:"#1d1d1f",fontFamily:F}}>
    <style>{`@keyframes spin{to{transform:rotate(360deg)}}body{margin:0;padding:0}input[type=number]::-webkit-inner-spin-button{opacity:1}`}</style>
    <div style={{background:"#1d1d1f",padding:"10px 24px",display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:10}}>
      <div style={{display:"flex",alignItems:"center",gap:16}}><SeatLogo/><div style={{width:1,height:20,background:"rgba(255,255,255,0.15)"}}/><div><div style={{fontSize:13,fontWeight:600,color:"#fff"}}>Marketing Dashboard</div><div style={{fontSize:10,color:"rgba(255,255,255,0.4)",display:"flex",alignItems:"center",gap:6,marginTop:1}}><div style={{width:5,height:5,borderRadius:"50%",background:status==="live"?"#34c759":"#ff9500"}}/>{status==="live"?"En vivo":"Cargando"}{lastUp&&` · ${lastUp.toLocaleTimeString("es-ES",{hour:"2-digit",minute:"2-digit"})}`}</div></div></div>
      <div style={{display:"flex",alignItems:"center",gap:6}}><div style={{background:"rgba(255,255,255,0.08)",borderRadius:10,padding:3,display:"flex",gap:2}}>{nb("overview","Resumen")}{nb("campaigns","Campañas")}{nb("budget","Presupuestos")}</div><button onClick={fetchData} disabled={loading} style={{background:"rgba(255,255,255,0.08)",border:"none",borderRadius:8,color:"#fff",fontFamily:F,fontSize:13,padding:"7px 12px",cursor:"pointer"}}>{loading?"···":"↻"}</button><button onClick={logout} style={{background:"transparent",border:"none",color:"rgba(255,255,255,0.35)",fontFamily:F,fontSize:11,padding:"7px 8px",cursor:"pointer"}}>Salir</button></div>
    </div>
    <div style={{height:2.5,background:"#e3000b"}}/>
    <div style={{padding:24,maxWidth:1440,margin:"0 auto"}}>
      {loading&&<div style={{display:"flex",flexDirection:"column",alignItems:"center",padding:"100px 0",gap:16}}><div style={{width:36,height:36,border:"3px solid #e5e5ea",borderTop:"3px solid #e3000b",borderRadius:"50%",animation:"spin 1s linear infinite"}}/><div style={{fontSize:13,color:"#6e6e73"}}>Cargando datos...</div></div>}

      {!loading&&data.length>0&&view==="overview"&&<>
        <div style={{marginBottom:20}}><DatePicker sd={sd} ed={ed} onChange={(s,e)=>{setSd(s);setEd(e);}}/></div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:14,marginBottom:20}}>
          <MC label="Inversión" total={fmt(tot.sp)} google={fmt(gA.sp)} meta={fmt(mA.sp)}/>
          <MC label="Impresiones" total={fN(tot.im)} google={fN(gA.im)} meta={fN(mA.im)}/>
          <MC label="Clics" total={fN(tot.cl)} google={fN(gA.cl)} meta={fN(mA.cl)}/>
          <MC label="CPC medio" total={fmt(tCPC)} google={fmt(gCPC)} meta={fmt(mCPC)}/>
          <MC label="CTR" total={fP(tCTR)} google={fP(gCTR)} meta={fP(mCTR)}/>
          <MC label="Conversiones" total={fN(tot.cv)} google={fN(gA.cv)} meta={fN(mA.cv)}/>
        </div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14,marginBottom:20}}><BG label="Google Ads" budget={tB*0.6} spent={gA.sp} color="#4285f4"/><BG label="Meta Ads" budget={tB*0.4} spent={mA.sp} color="#0668E1"/></div>
        <div style={{marginBottom:20}}><BCT budgets={mb} ms={ms} cm={cm}/></div>
        <div style={{display:"grid",gridTemplateColumns:"5fr 2fr",gap:14,marginBottom:20}}>
          <div style={{background:"#fff",borderRadius:14,padding:20,boxShadow:C.shadow,border:`1px solid ${C.border}`}}><div style={{fontSize:11,color:"#aeaeb2",letterSpacing:0.5,textTransform:"uppercase",fontWeight:600,marginBottom:16}}>Inversión diaria</div><ResponsiveContainer width="100%" height={220}><AreaChart data={daily}><defs><linearGradient id="gG" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4285f4" stopOpacity={0.15}/><stop offset="100%" stopColor="#4285f4" stopOpacity={0}/></linearGradient><linearGradient id="mG" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#0668E1" stopOpacity={0.15}/><stop offset="100%" stopColor="#0668E1" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0"/><XAxis dataKey="fecha" tick={{fill:"#aeaeb2",fontSize:10}} tickFormatter={v=>v.slice(5)}/><YAxis tick={{fill:"#aeaeb2",fontSize:10,fontFamily:FM}} tickFormatter={v=>`${v}€`}/><Tooltip contentStyle={{background:"#fff",border:"1px solid #e5e5ea",borderRadius:10,fontFamily:F,fontSize:12,boxShadow:C.shadowMd}} formatter={(v,n)=>[`${parseFloat(v).toFixed(2)} €`,n]}/><Area type="monotone" dataKey="google" stackId="1" stroke="#4285f4" fill="url(#gG)" name="Google Ads" strokeWidth={1.5}/><Area type="monotone" dataKey="meta" stackId="1" stroke="#0668E1" fill="url(#mG)" name="Meta Ads" strokeWidth={1.5}/></AreaChart></ResponsiveContainer></div>
          <div style={{background:"#fff",borderRadius:14,padding:20,boxShadow:C.shadow,border:`1px solid ${C.border}`,display:"flex",flexDirection:"column"}}><div style={{fontSize:11,color:"#aeaeb2",letterSpacing:0.5,textTransform:"uppercase",fontWeight:600,marginBottom:16}}>Distribución</div><div style={{flex:1,display:"flex",alignItems:"center"}}><ResponsiveContainer width="100%" height={160}><PieChart><Pie data={piD} cx="50%" cy="50%" innerRadius={45} outerRadius={65} dataKey="value" stroke="none" paddingAngle={2}>{piD.map((e,i)=><Cell key={i} fill={e.color}/>)}</Pie><Tooltip contentStyle={{background:"#fff",border:"1px solid #e5e5ea",borderRadius:10,fontFamily:F,fontSize:12}} formatter={v=>fmt(v)}/></PieChart></ResponsiveContainer></div><div style={{display:"flex",flexDirection:"column",gap:8,marginTop:8}}>{piD.map(p=>(<div key={p.name} style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:8,height:8,borderRadius:"50%",background:p.color}}/><span style={{fontSize:12,color:"#6e6e73",flex:1}}>{p.name}</span><span style={{fontSize:13,fontWeight:600,fontFamily:FM}}>{tot.sp>0?((p.value/tot.sp)*100).toFixed(0):0}%</span></div>))}</div></div>
        </div>
        <div style={{background:"#fff",borderRadius:14,padding:20,boxShadow:C.shadow,border:`1px solid ${C.border}`}}><div style={{fontSize:11,color:"#aeaeb2",letterSpacing:0.5,textTransform:"uppercase",fontWeight:600,marginBottom:16}}>Clics y conversiones</div><ResponsiveContainer width="100%" height={180}><LineChart data={daily}><CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0"/><XAxis dataKey="fecha" tick={{fill:"#aeaeb2",fontSize:10}} tickFormatter={v=>v.slice(5)}/><YAxis yAxisId="l" tick={{fill:"#aeaeb2",fontSize:10,fontFamily:FM}}/><YAxis yAxisId="r" orientation="right" tick={{fill:"#aeaeb2",fontSize:10,fontFamily:FM}}/><Tooltip contentStyle={{background:"#fff",border:"1px solid #e5e5ea",borderRadius:10,fontFamily:F,fontSize:12}}/><Line yAxisId="l" type="monotone" dataKey="clics" stroke="#e3000b" strokeWidth={1.5} dot={false} name="Clics"/><Line yAxisId="r" type="monotone" dataKey="conv" stroke="#34c759" strokeWidth={1.5} dot={false} name="Conversiones"/></LineChart></ResponsiveContainer></div>
      </>}

      {!loading&&data.length>0&&view==="campaigns"&&<>
        <div style={{marginBottom:20}}><DatePicker sd={sd} ed={ed} onChange={(s,e)=>{setSd(s);setEd(e);}}/></div>
        <div style={{background:"#fff",borderRadius:14,overflow:"hidden",boxShadow:C.shadow,border:`1px solid ${C.border}`}}>
          <div style={{padding:"16px 20px",background:"#1d1d1f",display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:3,height:16,background:"#e3000b",borderRadius:2}}/><span style={{fontSize:13,color:"#fff",fontWeight:600}}>Campañas</span></div><span style={{fontSize:12,color:"rgba(255,255,255,0.4)"}}>{camps.length} campañas</span></div>
          <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontFamily:F,fontSize:13}}><thead><tr style={{background:"#fafafa"}}>{["Plataforma","Campaña","Estado","Inversión","Clics","Impresiones","CTR","CPC","Conversiones"].map(h=>(<th key={h} style={{padding:"11px 14px",textAlign:h==="Plataforma"||h==="Campaña"||h==="Estado"?"left":"right",color:"#aeaeb2",fontWeight:600,fontSize:10,letterSpacing:0.5,textTransform:"uppercase",borderBottom:`1px solid ${C.border}`}}>{h}</th>))}</tr></thead><tbody>{camps.map((c,i)=>{const ctr=c.im>0?(c.cl/c.im)*100:0,cpc=c.cl>0?c.co/c.cl:0,pc=c.pl==="Google Ads"?"#4285f4":"#0668E1";return(<tr key={i} style={{borderBottom:`1px solid ${C.border}`}}><td style={{padding:"11px 14px"}}><div style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:7,height:7,borderRadius:"50%",background:pc}}/><span style={{color:pc,fontWeight:600,fontSize:12}}>{c.pl==="Google Ads"?"Google":"Meta"}</span></div></td><td style={{padding:"11px 14px",fontWeight:500,maxWidth:240,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{c.ca}</td><td style={{padding:"11px 14px"}}><span style={{background:c.es==="ACTIVE"||c.es==="ENABLED"?"#e5f9ed":"#f0f0f0",color:c.es==="ACTIVE"||c.es==="ENABLED"?"#34c759":"#aeaeb2",padding:"3px 10px",borderRadius:20,fontSize:11,fontWeight:600}}>{c.es==="ACTIVE"||c.es==="ENABLED"?"Activa":"Pausa"}</span></td><td style={{padding:"11px 14px",textAlign:"right",fontWeight:700,fontFamily:FM,fontSize:12}}>{fmt(c.co)}</td><td style={{padding:"11px 14px",textAlign:"right",fontFamily:FM,fontSize:12,color:"#6e6e73"}}>{fN(c.cl)}</td><td style={{padding:"11px 14px",textAlign:"right",fontFamily:FM,fontSize:12,color:"#6e6e73"}}>{fN(c.im)}</td><td style={{padding:"11px 14px",textAlign:"right",fontFamily:FM,fontSize:12,color:"#6e6e73"}}>{fP(ctr)}</td><td style={{padding:"11px 14px",textAlign:"right",fontFamily:FM,fontSize:12,color:"#6e6e73"}}>{fmt(cpc)}</td><td style={{padding:"11px 14px",textAlign:"right",fontWeight:600,fontFamily:FM,fontSize:12,color:"#34c759"}}>{fN(c.cv)}</td></tr>);})}</tbody></table></div>
        </div>
      </>}

      {!loading&&view==="budget"&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20}}><BE budgets={mb} onChange={saveMb}/><BCT budgets={mb} ms={ms} cm={cm}/></div>}

      {!loading&&data.length===0&&view!=="budget"&&<div style={{textAlign:"center",padding:"100px 0"}}><div style={{fontSize:40,marginBottom:16}}>📊</div><div style={{fontSize:17,fontWeight:600,marginBottom:6}}>Sin datos todavía</div><div style={{fontSize:13,color:"#6e6e73",maxWidth:360,margin:"0 auto"}}>Los datos llegarán automáticamente cuando se ejecuten los flujos.</div></div>}
    </div>
  </div>);
}
